# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"WandbCallback": "00_core.ipynb",
         "log_dataset": "00_core.ipynb",
         "log_model": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/wandbfastai/"

git_url = "https://github.com/fastai/wandbfastai/tree/master/"

def custom_doc_links(name): return None
